framework:
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            cache.redis:
                adapter: cache.adapter.redis
                provider: 'redis://redis:6379'