doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            cart_id: App\Shared\Infrastructure\Doctrine\Type\CartIdType
            product_id: App\Shared\Infrastructure\Doctrine\Type\ProductIdType
            money: App\Shared\Infrastructure\Doctrine\Type\MoneyType
            quantity: App\Shared\Infrastructure\Doctrine\Type\QuantityType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Cart:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Cart/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Cart\Domain\Entity'
                alias: Cart