doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        server_version: '15'

    # ORM deshabilitado completamente
    # orm:
    #     auto_generate_proxy_classes: true
    #     auto_mapping: true